export interface Province {
  id: string;
  name: string;
  districts: string[];
}

export const PROVINCES: Province[] = [
  { id: 'adana', name: 'Adana', districts: ['Seyhan', 'Yüreğir', 'Çukurova', 'Sarıçam', 'Ceyhan', 'Kozan', 'Karaisalı', 'Pozantı', 'Feke', 'İmamoğlu', 'Karataş', 'Tufanbeyli', 'Yumurtalık', 'Aladağ', 'Saimbeyli'] },
  { id: 'adiyaman', name: 'Adıyaman', districts: ['Merkez', 'Besni', 'Çelikhan', 'Gerger', 'Gölbaşı', 'Kahta', 'Samsat', 'Sincik', 'Tut'] },
  { id: 'afyonkarahisar', name: 'Afyonkarahisar', districts: ['Merkez', 'Bolvadin', 'Çay', 'Dinar', 'Emirdağ', 'İhsaniye', 'Sandıklı', 'Sinanpaşa', 'Sultandağı', 'Şuhut', 'Başmakçı', 'Bayat', 'Çobanlar', 'Dazkırı', 'Evciler', 'Hocalar', 'Kızılören'] },
  { id: 'agri', name: 'Ağrı', districts: ['Merkez', 'Diyadin', 'Doğubayazıt', 'Eleşkirt', 'Hamur', 'Patnos', 'Taşlıçay', 'Tutak'] },
  { id: 'aksaray', name: 'Aksaray', districts: ['Merkez', 'Ağaçören', 'Eskil', 'Gülağaç', 'Güzelyurt', 'Ortaköy', 'Sarıyahşi'] },
  { id: 'amasya', name: 'Amasya', districts: ['Merkez', 'Göynücek', 'Gümüşhacıköy', 'Merzifon', 'Suluova', 'Taşova', 'Hamamözü'] },
  { id: 'ankara', name: 'Ankara', districts: ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan', 'Altındağ', 'Pursaklar', 'Gölbaşı', 'Polatlı', 'Beypazarı', 'Çubuk', 'Elmadağ', 'Haymana', 'Kalecik', 'Kızılcahamam', 'Nallıhan', 'Şereflikoçhisar', 'Akyurt', 'Ayaş', 'Bala', 'Çamlıdere', 'Evren', 'Güdül', 'Kahramankazan'] },
  { id: 'antalya', name: 'Antalya', districts: ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Alanya', 'Manavgat', 'Serik', 'Aksu', 'Döşemealtı', 'Kaş', 'Kemer', 'Kumluca', 'Finike', 'Gazipaşa', 'Elmalı', 'Demre', 'Akseki', 'İbradı', 'Korkuteli', 'Gündoğmuş'] },
  { id: 'ardahan', name: 'Ardahan', districts: ['Merkez', 'Çıldır', 'Göle', 'Hanak', 'Posof', 'Damal'] },
  { id: 'artvin', name: 'Artvin', districts: ['Merkez', 'Arhavi', 'Borçka', 'Hopa', 'Şavşat', 'Yusufeli', 'Ardanuç', 'Murgul'] },
  { id: 'aydin', name: 'Aydın', districts: ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim', 'İncirliova', 'Çine', 'Germencik', 'Bozdoğan', 'Karacasu', 'Köşk', 'Sultanhisar', 'Yenipazar', 'Buharkent', 'Karpuzlu', 'Koçarlı', 'Kuyucak'] },
  { id: 'balikesir', name: 'Balıkesir', districts: ['Altıeylül', 'Karesi', 'Bandırma', 'Edremit', 'Gönen', 'Ayvalık', 'Burhaniye', 'Erdek', 'Susurluk', 'Bigadiç', 'Dursunbey', 'Havran', 'İvrindi', 'Sındırgı', 'Balya', 'Gömeç', 'Kepsut', 'Manyas', 'Marmara', 'Savaştepe'] },
  { id: 'bartin', name: 'Bartın', districts: ['Merkez', 'Amasra', 'Kurucaşile', 'Ulus'] },
  { id: 'batman', name: 'Batman', districts: ['Merkez', 'Beşiri', 'Gercüş', 'Hasankeyf', 'Kozluk', 'Sason'] },
  { id: 'bayburt', name: 'Bayburt', districts: ['Merkez', 'Aydıntepe', 'Demirözü'] },
  { id: 'bilecik', name: 'Bilecik', districts: ['Merkez', 'Bozüyük', 'Osmaneli', 'Pazaryeri', 'Söğüt', 'Gölpazarı', 'İnhisar', 'Yenipazar'] },
  { id: 'bingol', name: 'Bingöl', districts: ['Merkez', 'Genç', 'Karlıova', 'Kiğı', 'Solhan', 'Adaklı', 'Yayladere', 'Yedisu'] },
  { id: 'bitlis', name: 'Bitlis', districts: ['Merkez', 'Ahlat', 'Adilcevaz', 'Güroymak', 'Hizan', 'Mutki', 'Tatvan'] },
  { id: 'bolu', name: 'Bolu', districts: ['Merkez', 'Düzce', 'Gerede', 'Göynük', 'Mudurnu', 'Mengen', 'Dörtdivan', 'Kıbrıscık', 'Seben', 'Yeniçağa'] },
  { id: 'burdur', name: 'Burdur', districts: ['Merkez', 'Bucak', 'Gölhisar', 'Tefenni', 'Yeşilova', 'Ağlasun', 'Altınyayla', 'Çavdır', 'Çeltikçi', 'Karamanlı', 'Kemer'] },
  { id: 'bursa', name: 'Bursa', districts: ['Osmangazi', 'Nilüfer', 'Yıldırım', 'Gemlik', 'İnegöl', 'Mudanya', 'Mustafakemalpaşa', 'Karacabey', 'Gürsu', 'Kestel', 'Orhangazi', 'İznik', 'Yenişehir', 'Büyükorhan', 'Harmancık', 'Keles', 'Orhaneli'] },
  { id: 'canakkale', name: 'Çanakkale', districts: ['Merkez', 'Biga', 'Çan', 'Gelibolu', 'Ayvacık', 'Bayramiç', 'Ezine', 'Lapseki', 'Yenice', 'Bozcaada', 'Eceabat', 'Gökçeada'] },
  { id: 'cankiri', name: 'Çankırı', districts: ['Merkez', 'Çerkeş', 'Eldivan', 'Ilgaz', 'Kurşunlu', 'Orta', 'Şabanözü', 'Yapraklı', 'Atkaracalar', 'Kızılırmak', 'Bayramören', 'Korgun'] },
  { id: 'corum', name: 'Çorum', districts: ['Merkez', 'Alaca', 'İskilip', 'Osmancık', 'Sungurlu', 'Bayat', 'Boğazkale', 'Dodurga', 'Kargı', 'Laçin', 'Mecitözü', 'Oğuzlar', 'Ortaköy', 'Uğurludağ'] },
  { id: 'denizli', name: 'Denizli', districts: ['Merkezefendi', 'Pamukkale', 'Acıpayam', 'Çal', 'Çivril', 'Sarayköy', 'Tavas', 'Buldan', 'Güney', 'Kale', 'Babadağ', 'Bekilli', 'Beyağaç', 'Bozkurt', 'Çameli', 'Çardak', 'Çardak', 'Honaz', 'Serinhisar'] },
  { id: 'diyarbakir', name: 'Diyarbakır', districts: ['Bağlar', 'Kayapınar', 'Sur', 'Yenişehir', 'Bismil', 'Çermik', 'Çınar', 'Çüngüş', 'Dicle', 'Eğil', 'Ergani', 'Hani', 'Hazro', 'Kocaköy', 'Kulp', 'Lice', 'Silvan'] },
  { id: 'duzce', name: 'Düzce', districts: ['Merkez', 'Akçakoca', 'Yığılca', 'Cumayeri', 'Gölyaka', 'Çilimli', 'Gümüşova', 'Kaynaşlı'] },
  { id: 'edirne', name: 'Edirne', districts: ['Merkez', 'Keşan', 'Uzunköprü', 'İpsala', 'Havsa', 'Enez', 'Lalapaşa', 'Meriç', 'Süloğlu'] },
  { id: 'elazig', name: 'Elazığ', districts: ['Merkez', 'Kovancılar', 'Karakoçan', 'Palu', 'Sivrice', 'Ağın', 'Alacakaya', 'Arıcak', 'Baskil', 'Keban', 'Maden'] },
  { id: 'erzincan', name: 'Erzincan', districts: ['Merkez', 'Çayırlı', 'İliç', 'Kemah', 'Kemaliye', 'Refahiye', 'Tercan', 'Üzümlü', 'Otlukbeli'] },
  { id: 'erzurum', name: 'Erzurum', districts: ['Yakutiye', 'Palandöken', 'Aziziye', 'Horasan', 'Oltu', 'İspir', 'Pasinler', 'Aşkale', 'Çat', 'Hınıs', 'Karayazı', 'Narman', 'Olur', 'Şenkaya', 'Tekman', 'Tortum', 'Karaçoban', 'Köprüköy', 'Pazaryolu', 'Uzundere'] },
  { id: 'eskisehir', name: 'Eskişehir', districts: ['Odunpazarı', 'Tepebaşı', 'Sivrihisar', 'Çifteler', 'Mahmudiye', 'Mihalıççık', 'Sarıcakaya', 'Seyitgazi', 'Alpu', 'Beylikova', 'İnönü', 'Günyüzü', 'Han', 'Mihalgazi'] },
  { id: 'gaziantep', name: 'Gaziantep', districts: ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye', 'Nurdağı', 'Oğuzeli', 'Yavuzeli', 'Araban', 'Karkamış'] },
  { id: 'giresun', name: 'Giresun', districts: ['Merkez', 'Bulancak', 'Espiye', 'Görele', 'Tirebolu', 'Şebinkarahisar', 'Alucra', 'Dereli', 'Doğankent', 'Eynesil', 'Güce', 'Keşap', 'Piraziz', 'Yağlıdere', 'Çamoluk', 'Çanakçı'] },
  { id: 'gumushane', name: 'Gümüşhane', districts: ['Merkez', 'Kelkit', 'Şiran', 'Torul', 'Köse', 'Kürtün'] },
  { id: 'hakkari', name: 'Hakkari', districts: ['Merkez', 'Yüksekova', 'Şemdinli', 'Çukurca'] },
  { id: 'hatay', name: 'Hatay', districts: ['Antakya', 'İskenderun', 'Defne', 'Arsuz', 'Dörtyol', 'Kırıkhan', 'Reyhanlı', 'Samandağ', 'Altınözü', 'Belen', 'Erzin', 'Hassa', 'Kumlu', 'Payas', 'Yayladağı'] },
  { id: 'igdir', name: 'Iğdır', districts: ['Merkez', 'Aralık', 'Karakoyunlu', 'Tuzluca'] },
  { id: 'isparta', name: 'Isparta', districts: ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç', 'Senirkent', 'Keçiborlu', 'Atabey', 'Gelendost', 'Gönen', 'Sütçüler', 'Uluborlu', 'Aksu', 'Yenişarbademli'] },
  { id: 'istanbul', name: 'İstanbul', districts: ['Kadıköy', 'Beşiktaş', 'Şişli', 'Üsküdar', 'Beyoğlu', 'Fatih', 'Bakırköy', 'Maltepe', 'Ümraniye', 'Pendik', 'Kartal', 'Ataşehir', 'Sarıyer', 'Eyüpsultan', 'Küçükçekmece', 'Bahçelievler', 'Gaziosmanpaşa', 'Sultangazi', 'Esenler', 'Güngören', 'Kağıthane', 'Bayrampaşa', 'Zeytinburnu', 'Bağcılar', 'Başakşehir', 'Avcılar', 'Büyükçekmece', 'Çatalca', 'Silivri', 'Arnavutköy', 'Çekmeköy', 'Sancaktepe', 'Sultanbeyli', 'Tuzla', 'Beykoz', 'Şile', 'Adalar', 'Esenyurt'] },
  { id: 'izmir', name: 'İzmir', districts: ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Çiğli', 'Gaziemir', 'Balçova', 'Bayraklı', 'Narlıdere', 'Karabağlar', 'Aliağa', 'Bergama', 'Menemen', 'Tire', 'Torbalı', 'Ödemiş', 'Urla', 'Çeşme', 'Foça', 'Kemalpaşa', 'Kiraz', 'Menderes', 'Seferihisar', 'Selçuk', 'Bayındır', 'Beydağ', 'Dikili', 'Güzelbahçe', 'Karaburun', 'Kınık'] },
  { id: 'kahramanmaras', name: 'Kahramanmaraş', districts: ['Dulkadiroğlu', 'Onikişubat', 'Elbistan', 'Afşin', 'Pazarcık', 'Göksun', 'Andırın', 'Türkoğlu', 'Çağlayancerit', 'Ekinözü', 'Nurhak'] },
  { id: 'karabuk', name: 'Karabük', districts: ['Merkez', 'Safranbolu', 'Yenice', 'Eflani', 'Eskipazar', 'Ovacık'] },
  { id: 'karaman', name: 'Karaman', districts: ['Merkez', 'Ermenek', 'Ayrancı', 'Kazımkarabekir', 'Başyayla', 'Sarıveliler'] },
  { id: 'kars', name: 'Kars', districts: ['Merkez', 'Kağızman', 'Sarıkamış', 'Selim', 'Susuz', 'Arpaçay', 'Digor', 'Akyaka'] },
  { id: 'kastamonu', name: 'Kastamonu', districts: ['Merkez', 'Tosya', 'Taşköprü', 'İnebolu', 'Cide', 'Devrekani', 'Araç', 'Bozkurt', 'Küre', 'Abana', 'Ağlı', 'Azdavay', 'Çatalzeytin', 'Daday', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'Pınarbaşı', 'Şenpazar', 'Seydiler'] },
  { id: 'kayseri', name: 'Kayseri', districts: ['Kocasinan', 'Melikgazi', 'Talas', 'Develi', 'İncesu', 'Yahyalı', 'Bünyan', 'Pınarbaşı', 'Sarıoğlan', 'Sarız', 'Tomarza', 'Akkışla', 'Felahiye', 'Hacılar', 'Özvatan', 'Yeşilhisar'] },
  { id: 'kilis', name: 'Kilis', districts: ['Merkez', 'Elbeyli', 'Musabeyli', 'Polateli'] },
  { id: 'kirikkale', name: 'Kırıkkale', districts: ['Merkez', 'Delice', 'Keskin', 'Sulakyurt', 'Bahşili', 'Balışeyh', 'Çelebi', 'Karakeçili', 'Yahşihan'] },
  { id: 'kirklareli', name: 'Kırklareli', districts: ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize', 'Pınarhisar', 'Demirköy', 'Kofçaz', 'Pehlivanköy'] },
  { id: 'kirsehir', name: 'Kırşehir', districts: ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı', 'Akpınar', 'Akçakent', 'Boztepe'] },
  { id: 'kocaeli', name: 'Kocaeli', districts: ['İzmit', 'Gebze', 'Körfez', 'Gölcük', 'Darıca', 'Çayırova', 'Derince', 'Kandıra', 'Karamürsel', 'Başiskele', 'Kartepe', 'Dilovası'] },
  { id: 'konya', name: 'Konya', districts: ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir', 'Beyşehir', 'Çumra', 'Seydişehir', 'Ilgın', 'Cihanbeyli', 'Karapınar', 'Kulu', 'Bozkır', 'Doğanhisar', 'Hadim', 'Sarayönü', 'Akören', 'Altınekin', 'Ahırlı', 'Çeltik', 'Derbent', 'Derebucak', 'Emirgazi', 'Güneysınır', 'Halkapınar', 'Hüyük', 'Kadınhanı', 'Taşkent', 'Tuzlukçu', 'Yalıhüyük', 'Yunak'] },
  { id: 'kutahya', name: 'Kütahya', districts: ['Merkez', 'Tavşanlı', 'Simav', 'Gediz', 'Emet', 'Altıntaş', 'Domaniç', 'Dumlupınar', 'Hisarcık', 'Şaphane', 'Aslanapa', 'Çavdarhisar', 'Pazarlar'] },
  { id: 'malatya', name: 'Malatya', districts: ['Battalgazi', 'Yeşilyurt', 'Akçadağ', 'Arapgir', 'Arguvan', 'Darende', 'Doğanşehir', 'Hekimhan', 'Pütürge', 'Yazıhan', 'Doğanyol', 'Kale', 'Kuluncak'] },
  { id: 'manisa', name: 'Manisa', districts: ['Şehzadeler', 'Yunusemre', 'Akhisar', 'Alaşehir', 'Salihli', 'Turgutlu', 'Soma', 'Kırkağaç', 'Demirci', 'Gördes', 'Sarıgöl', 'Saruhanlı', 'Selendi', 'Ahmetli', 'Gölmarmara', 'Köprübaşı'] },
  { id: 'mardin', name: 'Mardin', districts: ['Artuklu', 'Kızıltepe', 'Midyat', 'Nusaybin', 'Derik', 'Mazıdağı', 'Savur', 'Dargeçit', 'Ömerli', 'Yeşilli'] },
  { id: 'mersin', name: 'Mersin', districts: ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Tarsus', 'Erdemli', 'Silifke', 'Anamur', 'Mut', 'Gülnar', 'Aydıncık', 'Bozyazı', 'Çamlıyayla'] },
  { id: 'mugla', name: 'Muğla', districts: ['Menteşe', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas', 'Datça', 'Köyceğiz', 'Ortaca', 'Ula', 'Yatağan', 'Dalaman', 'Kavaklıdere', 'Seydikemer'] },
  { id: 'mus', name: 'Muş', districts: ['Merkez', 'Bulanık', 'Malazgirt', 'Varto', 'Hasköy', 'Korkut'] },
  { id: 'nevsehir', name: 'Nevşehir', districts: ['Merkez', 'Avanos', 'Ürgüp', 'Gülşehir', 'Derinkuyu', 'Kozaklı', 'Acıgöl', 'Hacıbektaş'] },
  { id: 'nigde', name: 'Niğde', districts: ['Merkez', 'Bor', 'Çamardı', 'Ulukışla', 'Altunhisar', 'Çiftlik'] },
  { id: 'ordu', name: 'Ordu', districts: ['Altınordu', 'Ünye', 'Fatsa', 'Perşembe', 'Kumru', 'Korgan', 'Gölköy', 'Mesudiye', 'Akkuş', 'Aybastı', 'Çamaş', 'Çatalpınar', 'Çaybaşı', 'Gülyalı', 'Gürgentepe', 'İkizce', 'Kabadüz', 'Kabataş', 'Ulubey'] },
  { id: 'osmaniye', name: 'Osmaniye', districts: ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Hasanbeyli', 'Sumbas', 'Toprakkale'] },
  { id: 'rize', name: 'Rize', districts: ['Merkez', 'Ardeşen', 'Çayeli', 'Pazar', 'Fındıklı', 'İkizdere', 'Kalkandere', 'Hemşin', 'İyidere', 'Derepazarı', 'Güneysu'] },
  { id: 'sakarya', name: 'Sakarya', districts: ['Adapazarı', 'Serdivan', 'Arifiye', 'Erenler', 'Hendek', 'Karasu', 'Sapanca', 'Akyazı', 'Geyve', 'Kaynarca', 'Pamukova', 'Taraklı', 'Ferizli', 'Karapürçek', 'Söğütlü', 'Kocaali'] },
  { id: 'samsun', name: 'Samsun', districts: ['İlkadım', 'Atakum', 'Canik', 'Tekkeköy', 'Bafra', 'Çarşamba', 'Terme', 'Vezirköprü', 'Havza', 'Alaçam', 'Kavak', '19 Mayıs', 'Asarcık', 'Ayvacık', 'Ladik', 'Salıpazarı', 'Yakakent'] },
  { id: 'sanliurfa', name: 'Şanlıurfa', districts: ['Eyyübiye', 'Haliliye', 'Karaköprü', 'Viranşehir', 'Suruç', 'Siverek', 'Birecik', 'Bozova', 'Ceylanpınar', 'Halfeti', 'Hilvan', 'Akçakale', 'Harran'] },
  { id: 'siirt', name: 'Siirt', districts: ['Merkez', 'Pervari', 'Kurtalan', 'Baykan', 'Eruh', 'Şirvan', 'Tillo'] },
  { id: 'sinop', name: 'Sinop', districts: ['Merkez', 'Boyabat', 'Ayancık', 'Gerze', 'Durağan', 'Erfelek', 'Türkeli', 'Dikmen', 'Saraydüzü'] },
  { id: 'sivas', name: 'Sivas', districts: ['Merkez', 'Şarkışla', 'Gemerek', 'Kangal', 'Yıldızeli', 'Zara', 'Divriği', 'Hafik', 'İmranlı', 'Suşehri', 'Gürün', 'Akıncılar', 'Altınyayla', 'Doğanşar', 'Gölova', 'Koyulhisar', 'Ulaş'] },
  { id: 'sirnak', name: 'Şırnak', districts: ['Merkez', 'Cizre', 'Silopi', 'İdil', 'Uludere', 'Beytüşşebap', 'Güçlükonak'] },
  { id: 'tekirdag', name: 'Tekirdağ', districts: ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Kapaklı', 'Ergene', 'Hayrabolu', 'Malkara', 'Muratlı', 'Saray', 'Şarköy', 'Marmaraereğlisi'] },
  { id: 'tokat', name: 'Tokat', districts: ['Merkez', 'Turhal', 'Erbaa', 'Niksar', 'Zile', 'Reşadiye', 'Almus', 'Artova', 'Başçiftlik', 'Pazar', 'Sulusaray', 'Yeşilyurt'] },
  { id: 'trabzon', name: 'Trabzon', districts: ['Ortahisar', 'Akçaabat', 'Araklı', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Çaykara', 'Dernekpazarı', 'Düzköy', 'Hayrat', 'Köprübaşı', 'Maçka', 'Of', 'Sürmene', 'Şalpazarı', 'Tonya', 'Vakfıkebir', 'Yomra'] },
  { id: 'tunceli', name: 'Tunceli', districts: ['Merkez', 'Çemişgezek', 'Hozat', 'Mazgirt', 'Nazımiye', 'Ovacık', 'Pertek', 'Pülümür'] },
  { id: 'usak', name: 'Uşak', districts: ['Merkez', 'Banaz', 'Eşme', 'Karahallı', 'Sivaslı', 'Ulubey'] },
  { id: 'van', name: 'Van', districts: ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş', 'Başkale', 'Çatak', 'Gevaş', 'Gürpınar', 'Muradiye', 'Özalp', 'Bahçesaray', 'Çaldıran', 'Saray'] },
  { id: 'yalova', name: 'Yalova', districts: ['Merkez', 'Çiftlikköy', 'Çınarcık', 'Altınova', 'Armutlu', 'Termal'] },
  { id: 'yozgat', name: 'Yozgat', districts: ['Merkez', 'Sorgun', 'Yerköy', 'Boğazlıyan', 'Akdağmadeni', 'Çayıralan', 'Çekerek', 'Sarıkaya', 'Şefaatli', 'Aydıncık', 'Çandır', 'Kadışehri', 'Saraykent', 'Yenifakılı'] },
  { id: 'zonguldak', name: 'Zonguldak', districts: ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek', 'Alaplı', 'Gökçebey', 'Kilimli', 'Kozlu'] },
];
